language: bash

services:
  - docker

before_install: >
  docker run -dit -p=110:110 -p=25:25 -p=995:995 -p=80:80 -p=443:443 -p=587:587 -p=993:993 -p=143:143 -p=465:465 -h "mail.example.com" --name="easymail" -v /etc/ssl/certs/:/etc/ssl/certs/ ubuntu:16.04 /bin/sh -c "if [ -f /run.sh ]; then bash /run.sh; fi; exec /bin/bash" &&
  docker exec easymail apt-get update &&
  docker exec easymail apt-get install git -y &&
  docker cp ../runeasymail/easymail/ easymail:/easymail &&
  docker exec easymail /bin/sh -c "echo 'HOSTNAME: test.exmaple.com' > /easymail/easy-mail-install.config" &&
  docker exec easymail /bin/sh -c "echo 'PASSWORD: testpassword' >> /easymail/easy-mail-install.config" &&
  docker exec easymail /bin/sh -c "echo 'IS_ON_DOCKER: true' >> /easymail/easy-mail-install.config" &&
  docker exec easymail /bin/sh -c "echo 'SSL_INSTALL_OWN: n' >> /easymail/easy-mail-install.config" &&
  docker exec easymail /bin/sh -c "echo 'SSL_CA_BUNDLE_FILE: /etc/dovecot/dovecot.pem' >> /easymail/easy-mail-install.config" &&
  docker exec easymail /bin/sh -c "echo 'SSL_PRIVATE_KEY_FILE: /etc/dovecot/private/dovecot.pem' >> /easymail/easy-mail-install.config"

script:
    - docker exec easymail bash /easymail/install.sh -c /easymail/easy-mail-install.config
